//============================================================================
/// \file
/// \ingroup    g_applib
/// \brief      Contains the version info interface definition.
//============================================================================
/// \copyright  GNU General Public License (GPL) Version 3
//
// Copyright 2012-2021 Herbert Thielen
//
// This file is part of the program 'koelner-phonetik',
// see https://gitlab.ai.it.hs-worms.de/swq/23s/koelner-phonetik
//
// This program is free software: you can redistribute it and/or modify
// it under the terms of the GNU General Public License as published by
// the Free Software Foundation, either version 3 of the License, or
// (at your option) any later version.
// 
// This program is distributed in the hope that it will be useful,
// but WITHOUT ANY WARRANTY; without even the implied warranty of
// MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
// GNU General Public License for more details.
// 
// You should have received a copy of the GNU General Public License
// along with this program.  If not, see <https://www.gnu.org/licenses/>.
//============================================================================

#if !defined(VERSIONINFO_H)
#define VERSIONINFO_H

#include <string>

/// \brief Provide version information generated by the build process.
/// \details This class provides access to the build and version information
/// generated automatically during the build process.
/// As this is static information only, the class only has static (class level)
/// members and methods.
class VersionInfo
{
    public:
        static std::string getVersion();    ///< Get the version provided by git.
        static std::string getBuildTag();   ///< Get the build tag provided by jenkins.

    private:
        static const std::string buildTag;
        static const std::string version;
};

#endif
